# Generated by Django 2.1.7 on 2019-02-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_card_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
